### PR TITLE
Add query-json

### PR DESCRIPTION
**Pull request by davesnx**

### CODE REVIEW

**Comment by fiatjaf** [comment]
We need an "alternative implementations" section.

**Comment by fiatjaf** [comment]
@davesnx can `query-json` be used as a library and Reason applications? I couldn't figure that out.

**Comment by davesnx** [comment]
It can, but isn't published with that in mind. 

Using it in Reason will mean running this: https://github.com/davesnx/query-json/blob/main/js/QueryJsonJs.re

**Comment by fiatjaf** [comment]
I've created a new "implementations" section on the top of the repo and changed some things: https://github.com/fiatjaf/awesome-jq/commit/e7fbdb119a8f7635cacee4f98401472f10455dd1

Take a look.

If you feel it is appropriate for Reason programmers you can also include query-json under the "Libraries" section.

**Comment by davesnx** [comment]
Makes total sense, felt weird when I opened the PR in the first place under `External libraries`

**Pull request merged**
